### ISSUE TITLE
socket.io.js ?

### ISSUE THREAD

**Issue by qing-lin-007** [nenadg/twitter-stream-visualization#1]
Thank you for your code! I am new to d3. After deployed your code in my server I found out that socket.io.js is missing, or am I making some mistake? Thanks.

**Comment by nenadg** [comment]
Hey, which version of node do you use? 
I've just cloned from repo and did `npm install` `npm start` and everything worked well.
Socket.io is already available since it's included in packages configuration.

**Comment by qing-lin-007** [comment]
Thanks! Everything works well now.
