### ISSUE TITLE
Stuck on CONNECTING STREAM ... 

### ISSUE THREAD

**Issue by RichardSnow** [nenadg/twitter-stream-visualization#2]
Hi! I just cloned this code to learn a bit about how it works and I'm having some trouble. 
The globe loaded just fine, but the CONNECTING STREAM... div never seems to disappear and none of the tweets show up. The console never seems to indicate a problem, it just says: 
sockety on...
io ready.
Streaming .... 
I uncommented your testing code in default.js's orthographic function just to be sure and those sample tweets loaded just fine, so it seems to be a connection problem, not a displaying one. I've been putting console.log() comments in several places trying to see where it gets stuck, but since they all seem to output just fine, I'm a bit stumped. 
Have you perhaps run into something similar while making this or would you know where to look? Or am I doing something wrong entirely?
Thanks in advance!

**Comment by nenadg** [comment]
Hey Richard, you should probably enter your api keys, instead of those present `shared/routes.js` (which are invalid). I don't know what else could be a problem, since it works fine at http://twitter-stream.statick.org/ :)

**Comment by RichardSnow** [comment]
Yep, that's exactly what it was.
Everything works fine now, thanks for the help!
